version: '3.8'

services:
  app:
    image: dekimasc/networkmonitor:latest
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      NETWORK: 192.168.1.0/24
      PORTS: 22,443,80
      INTERVAL: 1.0
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: mysecretpassword
      DB_NAME: network_monitoring
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5000
      FLASK_DEBUG: True
      SPD_TEST: True

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: network_monitoring
    volumes:
      - db_data:/var/lib/mysql
      - ./base.sql:/docker-entrypoint-initdb.d/base.sql

volumes:
  db_data: